### ISSUE TITLE
error invalid syntax when startup

### ISSUE THREAD

**Issue by ghost** [asuiu/pyxtension#14]
Hi there, got strange error,

i installed 2 version, local and prods server, but on prod server it gives me error like this :

Traceback (most recent call last):
  File "versi1_telebot.py", line 1, in <module>
    from pyxtension.Json import Json
  File "/usr/local/lib/python3.5/dist-packages/pyxtension/Json.py", line 14, in <module>
    from pyxtension.streams import *
  File "/usr/local/lib/python3.5/dist-packages/pyxtension/streams.py", line 45
    _IDENTITY_FUNC: Callable[[T], T] = lambda _: _
                  ^
SyntaxError: invalid syntax

**Comment by pakesusu** [comment]
the program still error when using latest version pyxtension 1.13

  File "<frozen importlib._bootstrap_external>", line 1123, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1104, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 541, in spec_from_file_location
  File "/usr/local/lib/python3.5/dist-packages/pyxtension-1.13.0-py3.5.egg/pyxtension/streams.py", line 41
    _IDENTITY_FUNC: Callable[[_T], _T] = lambda _: _
                  ^
SyntaxError: invalid syntax

**Comment by asuiu** [comment]
Hi @ghost. Apologize for late answer.
The idea is that Pyxtension is compatible with Python 3.6 and up, as it uses type hint syntax that Py3.5 lacks.
It's compatible with Py2.7.x, and 3.6+. I've decided to drop the support of older versions of 3.x as all these entered in "security fixes only" mode and its[ end of life is quite close: 2020-09-13](https://devguide.python.org/#status-of-python-branches).
Just upgrade your Python version to any newer version (3.6+) and it should work
